version: '{build}'
image: Visual Studio 2017
skip_commits:
 files:
   - docs/*
   - '**/*.md'

# Only fetch the latest commits to reduce time to download on agent, but support pushes containing multiple commits
clone_depth: 50

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

build_script:
- ps: |
    #####################################
    # Build, test, pack and push nugets
    #####################################

    .\\build-with-wrc.bat
    $BuildExitCode = $LASTEXITCODE

    #####################################
    # Upload test results to AppVeyor
    #####################################

    $wc = New-Object 'System.Net.WebClient'

    if (Test-Path .\\Artifacts\\Logs\\) {
        Get-ChildItem .\\Artifacts\\Logs\\*Test*.xml | %{
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $_.FullName)
        }
    }

    if ($BuildExitCode -ne 0) {
        Write-Host "Build failed with exit code $BuildExitCode."
        exit $BuildExitCode
    }

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
test: off

artifacts:
- path: Artifacts\UnitsNet.zip
- path: 'Artifacts\NuGet\*.nupkg' # find all NuGet packages recursively

deploy:
- provider: NuGet
  api_key:
    secure: NlJ+D6kXfgU6RgRuf9okylLDENp8DA3tTRSC6UHBNbRS9ZAvRrC3Z0++Mr5VtGvz
  on:
    branch: master

- provider: NuGet
  api_key:
    secure: NlJ+D6kXfgU6RgRuf9okylLDENp8DA3tTRSC6UHBNbRS9ZAvRrC3Z0++Mr5VtGvz
  on:
    branch: release/*
