//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum AccelerationUnit
    {
        Undefined = 0,
        CentilightsecondPerHourSquared,
        CentimeterPerHourSquared,
        CentimeterPerMinuteSquared,
        CentimeterPerSecondSquared,
        DecalightsecondPerHourSquared,
        DecameterPerHourSquared,
        DecameterPerMinuteSquared,
        DecameterPerSecondSquared,
        DecilightsecondPerHourSquared,
        DecimeterPerHourSquared,
        DecimeterPerMinuteSquared,
        DecimeterPerSecondSquared,
        ExameterPerHourSquared,
        ExameterPerMinuteSquared,
        ExameterPerSecondSquared,
        FemtometerPerHourSquared,
        FemtometerPerMinuteSquared,
        FemtometerPerSecondSquared,
        FootPerSecondSquared,
        GigameterPerHourSquared,
        GigameterPerMinuteSquared,
        GigameterPerSecondSquared,
        HectometerPerHourSquared,
        HectometerPerMinuteSquared,
        HectometerPerSecondSquared,
        InchPerSecondSquared,
        KilolightsecondPerHourSquared,
        KilometerPerHourSquared,
        KilometerPerMinuteSquared,
        KilometerPerSecondSquared,
        KnotPerHour,
        KnotPerMinute,
        KnotPerSecond,
        LightsecondPerHourSquared,
        MegameterPerHourSquared,
        MegameterPerMinuteSquared,
        MegameterPerSecondSquared,
        MeterPerHourSquared,
        MeterPerMinuteSquared,
        MeterPerSecondSquared,
        MicrolightsecondPerHourSquared,
        MicrometerPerHourSquared,
        MicrometerPerMinuteSquared,
        MicrometerPerSecondSquared,
        MilePerHourSquared,
        MillilightsecondPerHourSquared,
        MillimeterPerHourSquared,
        MillimeterPerMinuteSquared,
        MillimeterPerSecondSquared,
        NanolightsecondPerHourSquared,
        NanometerPerHourSquared,
        NanometerPerMinuteSquared,
        NanometerPerSecondSquared,
        PetameterPerHourSquared,
        PetameterPerMinuteSquared,
        PetameterPerSecondSquared,
        PicometerPerHourSquared,
        PicometerPerMinuteSquared,
        PicometerPerSecondSquared,
        QutrameterPerHourSquared,
        QutrameterPerMinuteSquared,
        QutrameterPerSecondSquared,
        StandardGravity,
        TerameterPerHourSquared,
        TerameterPerMinuteSquared,
        TerameterPerSecondSquared,
        VettameterPerHourSquared,
        VettameterPerMinuteSquared,
        VettameterPerSecondSquared,
        YottameterPerHourSquared,
        YottameterPerMinuteSquared,
        YottameterPerSecondSquared,
        ZettameterPerHourSquared,
        ZettameterPerMinuteSquared,
        ZettameterPerSecondSquared,
    }

    #pragma warning restore 1591
}
