//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum IrradianceUnit
    {
        Undefined = 0,
        AttowattPerSquareCentimeter,
        AttowattPerSquareMeter,
        CentiwattPerSquareCentimeter,
        CentiwattPerSquareMeter,
        DecawattPerSquareCentimeter,
        DecawattPerSquareMeter,
        DeciwattPerSquareCentimeter,
        DeciwattPerSquareMeter,
        ExawattPerSquareCentimeter,
        ExawattPerSquareMeter,
        FemtowattPerSquareCentimeter,
        FemtowattPerSquareMeter,
        GigawattPerSquareCentimeter,
        GigawattPerSquareMeter,
        HectowattPerSquareCentimeter,
        HectowattPerSquareMeter,
        KilowattPerSquareCentimeter,
        KilowattPerSquareMeter,
        MegawattPerSquareCentimeter,
        MegawattPerSquareMeter,
        MicrowattPerSquareCentimeter,
        MicrowattPerSquareMeter,
        MilliwattPerSquareCentimeter,
        MilliwattPerSquareMeter,
        NanowattPerSquareCentimeter,
        NanowattPerSquareMeter,
        PetawattPerSquareCentimeter,
        PetawattPerSquareMeter,
        PicowattPerSquareCentimeter,
        PicowattPerSquareMeter,
        QutrawattPerSquareCentimeter,
        QutrawattPerSquareMeter,
        TerawattPerSquareCentimeter,
        TerawattPerSquareMeter,
        VettawattPerSquareCentimeter,
        VettawattPerSquareMeter,
        WattPerSquareCentimeter,
        WattPerSquareMeter,
        YoctowattPerSquareCentimeter,
        YoctowattPerSquareMeter,
        YottawattPerSquareCentimeter,
        YottawattPerSquareMeter,
        ZeptowattPerSquareCentimeter,
        ZeptowattPerSquareMeter,
        ZettawattPerSquareCentimeter,
        ZettawattPerSquareMeter,
    }

    #pragma warning restore 1591
}
