//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated (once) by \generate-code.bat, but will not be
//     regenerated when it already exists. The purpose of creating this file is to make
//     it easier to remember to implement all the unit conversion test cases.
//
//     Whenever a new unit is added to this quantity and \generate-code.bat is run,
//     the base test class will get a new abstract property and cause a compile error
//     in this derived class, reminding the developer to implement the test case
//     for the new unit.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.


using System;

namespace UnitsNet.Tests.CustomCode
{
    public class IlluminanceTests : IlluminanceTestsBase
    {
        protected override double FemtoluxInOneLux => 1e15;
        protected override double PicoluxInOneLux => 1e12;
        protected override double NanoluxInOneLux => 1e9;
        protected override double MicroluxInOneLux => 1e6;
        protected override double MilliluxInOneLux => 1E3;
        protected override double CentiluxInOneLux => 1e2;
        protected override double DeciluxInOneLux => 1e1;
        protected override double LuxInOneLux => 1;
        protected override double DecaluxInOneLux => 1e-1;
        protected override double HectoluxInOneLux => 1e-2;
        protected override double KiloluxInOneLux => 1E-3;
        protected override double MegaluxInOneLux => 1E-6;
        protected override double GigaluxInOneLux => 1e-9;
        protected override double TeraluxInOneLux => 1e-12;
        protected override double PetaluxInOneLux => 1e-15;
        protected override double ExaluxInOneLux => 1e-18;
        protected override double ZettaluxInOneLux => 1e-21;
        protected override double YottaluxInOneLux => 1e-24;
        protected override double QutraluxInOneLux => 1e-27;
        protected override double VettaluxInOneLux => 1e-30;
    }
}
