//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated (once) by \generate-code.bat, but will not be
//     regenerated when it already exists. The purpose of creating this file is to make
//     it easier to remember to implement all the unit conversion test cases.
//
//     Whenever a new unit is added to this quantity and \generate-code.bat is run,
//     the base test class will get a new abstract property and cause a compile error
//     in this derived class, reminding the developer to implement the test case
//     for the new unit.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.


using System;

namespace UnitsNet.Tests.CustomCode
{
    public class SpecificEntropyTests : SpecificEntropyTestsBase
    {
         protected override double BtusPerPoundFahrenheitInOneJoulePerKilogramKelvin => 2.3884589662749594e-4;

        protected override double FemtocaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e11;
        protected override double PicocaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e8;
        protected override double NanocaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e5;
        protected override double MicrocaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e2;
        protected override double MillicaloriesPerGramKelvinInOneJoulePerKilogramKelvin => 2.390057e-1;
        protected override double CenticaloriesPerGramKelvinInOneJoulePerKilogramKelvin => 2.390057e-2;
        protected override double DecicaloriesPerGramKelvinInOneJoulePerKilogramKelvin => 2.390057e-3;
        protected override double CaloriesPerGramKelvinInOneJoulePerKilogramKelvin => 2.390057e-4;
        protected override double DecacaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-5;
        protected override double HectocaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-6;
        protected override double KilocaloriesPerGramKelvinInOneJoulePerKilogramKelvin => 2.390057e-7;
        protected override double MegacaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-10;
        protected override double GigacaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-13;
        protected override double TeracaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-16;
        protected override double PetacaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-19;
        protected override double ExacaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-22;
        protected override double ZettacaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-25;
        protected override double YottacaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-28;
        protected override double QutracaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-31;
        protected override double VettacaloriesPerGramKelvinInOneJoulePerKilogramKelvin =>2.390057e-34;

        protected override double FemtojoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e15;
        protected override double PicojoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e12;
        protected override double NanojoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e9;
        protected override double MicrojoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e6;
        protected override double MillijoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e3;
        protected override double CentijoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e2;
        protected override double DecijoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e1;
        protected override double JoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e0;
        protected override double DecajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-1;
        protected override double HectojoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-2;
        protected override double KilojoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-3;
        protected override double MegajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-6;
        protected override double GigajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-9;
        protected override double TerajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-12;
        protected override double PetajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-15;
        protected override double ExajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-18;
        protected override double ZettajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-21;
        protected override double YottajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-24;
        protected override double QutrajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-27;
        protected override double VettajoulesPerKilogramDegreeCelsiusInOneJoulePerKilogramKelvin => 1e-30;

        protected override double FemtojoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e15;
        protected override double PicojoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e12;
        protected override double NanojoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e9;
        protected override double MicrojoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e6;
        protected override double MillijoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e3;
        protected override double CentijoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e2;
        protected override double DecijoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e1;
        protected override double JoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e0;
        protected override double DecajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin  => 1e-1;
        protected override double HectojoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e-2;
        protected override double KilojoulesPerKilogramKelvinInOneJoulePerKilogramKelvin  => 1e-3;
        protected override double MegajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin  => 1e-6;
        protected override double GigajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin  => 1e-9;
        protected override double TerajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin  => 1e-12;
        protected override double PetajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin  => 1e-15;
        protected override double ExajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin   => 1e-18;
        protected override double ZettajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e-21;
        protected override double YottajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e-24;
        protected override double QutrajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e-27;
        protected override double VettajoulesPerKilogramKelvinInOneJoulePerKilogramKelvin => 1e-30;
    }
}
